name: instagram_clone
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  vrouter: ^1.2.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/icons/feed/

    #mock: (Must be removed when api is ready)
    - assets/mock/feed/images/


  fonts:
    - family: proxima
      fonts:
        - asset: fonts/proxima/regular.ttf
#        - asset: fonts/proxima/medium.ttf
#        - asset: fonts/proxima/light.ttf
#        - asset: fonts/proxima/bold.ttf
#        - asset: fonts/proxima/semi-bold.ttf
#        - asset: fonts/proxima/black.ttf

    - family: bill
      fonts:
        - asset: fonts/Billabong/Billabong.ttf